import Head from 'next/head';
import detectEthereumProvider from '@metamask/detect-provider';
import { useEffect, useState } from 'react';
import Coffee from './Coffee';

declare global {
	interface Window {
		ethereum: any;
	}
}

export default function Home() {
	const [connected, setConnected] = useState(false);

	const connectMetaMask = async () => {
		const provider = await detectEthereumProvider();
		if (provider) {
			console.log('You have MetaMask!');
			const { ethereum } = window;
			await ethereum.request({ method: 'eth_requestAccounts' });
			setConnected(true);
			console.log('connected');
		}
		// no metamask plugin
		else {
			setConnected(false);
			console.log('Please install MetaMask!');
		}
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>Buy me a coffee</h1>
				<a href="https://goerli.etherscan.io/address/0xfcec1d6789591396751ffa4653fca4213bd26d73">contract address</a>
				{connected ? <Coffee /> : <button onClick={connectMetaMask}>Connect your wallet</button>}
			</main>
		</>
	);
}
